from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.pdfbase.pdfmetrics import stringWidth


def generate_pdf(review):

    filename = "review_report.pdf"

    pdf = canvas.Canvas(filename, pagesize=A4)

    width, height = A4

    y = height - 50

    # --------------------------------------------------
    # Helper: New Page
    # --------------------------------------------------

    def new_page():
        nonlocal y

        pdf.showPage()
        y = height - 50

    # --------------------------------------------------
    # Helper: Check Space
    # --------------------------------------------------

    def check_space(required_space=40):

        nonlocal y

        if y < required_space:
            new_page()

    # --------------------------------------------------
    # Helper: Draw Wrapped Text
    # --------------------------------------------------

    def draw_text(text, x=50, font="Helvetica", size=10):

        nonlocal y

        pdf.setFont(font, size)

        max_width = width - 100

        words = str(text).split()

        line = ""

        for word in words:

            test_line = line + " " + word

            if stringWidth(test_line, font, size) <= max_width:
                line = test_line
            else:

                check_space(50)

                pdf.drawString(
                    x,
                    y,
                    line.strip()
                )

                y -= 15

                line = word

        if line:

            check_space(50)

            pdf.drawString(
                x,
                y,
                line.strip()
            )

            y -= 15

    # --------------------------------------------------
    # Title
    # --------------------------------------------------

    pdf.setFont("Helvetica-Bold", 20)

    pdf.drawString(
        50,
        y,
        "AI Code Review Report"
    )

    y -= 40

    # --------------------------------------------------
    # Score
    # --------------------------------------------------

    score = review.get("score", 0)

    pdf.setFont("Helvetica-Bold", 14)

    pdf.drawString(
        50,
        y,
        f"Code Quality Score: {score}/100"
    )

    y -= 35

    # --------------------------------------------------
    # Sections
    # --------------------------------------------------

    sections = [
        ("Bugs", review.get("bugs", [])),
        ("Security", review.get("security", [])),
        ("Performance", review.get("performance", [])),
        ("Best Practices", review.get("best_practices", []))
    ]

    for section_name, issues in sections:

        check_space(100)

        pdf.setFont(
            "Helvetica-Bold",
            15
        )

        pdf.drawString(
            50,
            y,
            section_name
        )

        y -= 25

        if not issues:

            draw_text(
                "No issues found."
            )

            y -= 10

            continue

        for issue in issues:

            check_space(120)

            severity = issue.get(
                "severity",
                "UNKNOWN"
            )

            confidence = issue.get(
                "confidence",
                0
            )

            pdf.setFont(
                "Helvetica-Bold",
                11
            )

            pdf.drawString(
                60,
                y,
                f"Severity: {severity}"
            )

            y -= 18

            draw_text(
                f"Confidence: {confidence}"
            )

            draw_text(
                f"Issue: {issue.get('issue', '')}"
            )

            draw_text(
                f"Explanation: {issue.get('explanation', '')}"
            )

            draw_text(
                f"Suggestion: {issue.get('suggestion', '')}"
            )

            y -= 15

    # --------------------------------------------------
    # Footer
    # --------------------------------------------------

    pdf.setFont(
        "Helvetica",
        8
    )

    pdf.setFillColor(
        colors.grey
    )

    pdf.drawString(
        50,
        25,
        "Generated by AI-Powered Code Review Bot"
    )

    pdf.save()

    return filename